version: '3.8'
services:
  #MySql
  db:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: book_manager
      MYSQL_USER: manager_user
      MYSQL_PASSWORD: manager_user
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
