spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf8
    username: book_manager
    password: book_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
